### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by ghanchi2000** [ThatGuySam/customer-chat-for-facebook#1]
I am getting these two errors, else plugin working perfectly, waiting for customer feedbacks

Error # 1
Notice: Undefined index: page in /wp-content/plugins/customer-chat-for-facebook/admin/class-customer-chat-for-facebook-admin.php on line 138
customer-chat-for-facebook 

Error # 2
Notice: screen_icon is deprecated since version 3.8.0 with no alternative available. in /wp-includes/functions.php on line 3841
Notice: get_screen_icon is deprecated since version 3.8.0 with no alternative available. in /wp-includes/functions.php on line 3841

**Comment by ThatGuySam** [comment]
Thanks for the heads up! 
Error #1 has already been fixed in the 1.0.3 branch, but those other 2 are new and it looks like the culprit is here: https://github.com/ThatGuySam/customer-chat-for-facebook/blob/2db10d332a2f9d9bb27088e581714b04ceb1d45e/admin/class-customer-chat-for-facebook-admin.php#L97

I'll get these updates out as soon as I can

**Comment by ThatGuySam** [comment]
Fixed!

https://github.com/ThatGuySam/customer-chat-for-facebook/commit/786df3d30bd8ddb907afed875af9377fe917354d
